version: '3.8'
services:
    database:
        container_name: planning_gantt_container
        image: 'amd64/mongo:4.4'
        # restart: always
        ports:
            - "${MONGODB_PORT}:27017"
        volumes:
            - mongo-db:/data/db
            - ./scripts/setup_replica.sh:/tmp/setup_replica.sh
            - ./keyfile:/tmp

        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
            MONGO_INITDB_DATABASE: admin

        entrypoint:
            [
                '/usr/bin/mongod',
                '--auth',
                '--keyFile',
                '/tmp/keyfile',
                '--replSet',
                'rsmongo1',
                '--bind_ip_all'
            ]

        env_file:
            - ./.env

volumes:
    mongo-db:
